//! Port of `pi-core/agent/test/harness/telemetry.test.ts` (the schema and
//! runtime-helper cases; the docs-regeneration case checks the checked-in
//! markdown against the same TS renderer and stays with the oracle script).

use std::sync::Arc;

use pi_core::agent::harness::telemetry::{
    agent_schema_versions, agent_telemetry_schemas, agent_typed_span_starter, ai_telemetry_schema,
    harness_telemetry_schema, span_attributes, start_ai_span, start_harness_span,
};
use pi_core::telemetry::{
    AttributeValue, InMemoryTelemetryContext, TelemetryContext, TelemetryContextExt,
    TelemetryParentDefinition,
};

#[test]
fn serializes_both_schemas_and_exposes_the_span_vocabularies() {
    // Round-trips through the same serde shape the TypeScript JSON.stringify
    // produces (the embedded payload is generated by the oracle script).
    let ai = serde_json::to_value(ai_telemetry_schema()).expect("ai schema serializes");
    let harness =
        serde_json::to_value(harness_telemetry_schema()).expect("harness schema serializes");
    assert_eq!(ai["version"], serde_json::json!(1));
    assert_eq!(harness["version"], serde_json::json!(1));

    let span_names = pi_core::agent::harness::telemetry::harness_span_names();
    assert_eq!(
        span_names,
        [
            "pi.harness.run",
            "pi.harness.compaction",
            "pi.harness.navigation",
            "pi.harness.checkpoint",
            "pi.harness.turn",
            "pi.harness.step",
            "pi.harness.tool",
            "pi.harness.hook",
            "pi.harness.sleep",
            "pi.harness.event_handler",
            "pi.session.write",
        ]
    );

    assert_eq!(
        pi_core::agent::harness::telemetry::ai_span_names(),
        ["pi.ai.request"]
    );

    assert_eq!(agent_schema_versions(), [1, 1]);
    assert_eq!(agent_telemetry_schemas().len(), 2);
}

#[test]
fn ai_request_start_attributes_match_the_schema() {
    let request = &ai_telemetry_schema().spans["pi.ai.request"];
    let mut required: Vec<&str> = request
        .start_attributes
        .iter()
        .filter(|(_, definition)| definition.required)
        .map(|(name, _)| name.as_str())
        .collect();
    required.sort_unstable();
    assert_eq!(
        required,
        [
            "pi.ai.api",
            "pi.ai.model",
            "pi.ai.operation",
            "pi.ai.provider",
            "pi.ai.streaming",
        ]
    );
    assert!(request.start_attributes.contains_key("pi.ai.deferred"));
    assert!(!request.start_attributes["pi.ai.deferred"].required);
    assert!(matches!(request.parents, TelemetryParentDefinition::Any));
}

#[test]
fn harness_run_spans_require_the_operation_start_attributes() {
    let run = &harness_telemetry_schema().spans["pi.harness.run"];
    for attribute in [
        "pi.session.id",
        "pi.lane.name",
        "pi.operation.id",
        "pi.operation.recovery",
        "pi.operation.kind",
    ] {
        assert!(
            run.start_attributes.contains_key(attribute),
            "missing {attribute}"
        );
    }
    let checkpoint = &harness_telemetry_schema().spans["pi.harness.checkpoint"];
    assert!(matches!(
        checkpoint.parents,
        TelemetryParentDefinition::Spans { .. }
    ));
}

#[tokio::test]
async fn starts_ai_and_harness_spans_through_one_context() {
    let context: Arc<dyn TelemetryContext> = Arc::new(InMemoryTelemetryContext::new());
    let result = start_ai_span(
        &context,
        "pi.ai.request",
        span_attributes([
            ("pi.ai.operation", AttributeValue::from("stream")),
            ("pi.ai.provider", AttributeValue::from("provider")),
            ("pi.ai.model", AttributeValue::from("model")),
            ("pi.ai.api", AttributeValue::from("api")),
            ("pi.ai.streaming", AttributeValue::from(true)),
        ]),
        |span| async move {
            span.set_attributes(span_attributes([(
                "pi.ai.response.stop_reason",
                AttributeValue::from("stop"),
            )]));
            "ai-done"
        },
    )
    .await;
    assert_eq!(result, "ai-done");

    let result = start_harness_span(
        &context,
        "pi.harness.step",
        span_attributes([
            ("pi.lane.name", AttributeValue::from("main")),
            ("pi.operation.id", AttributeValue::from("operation")),
            ("pi.step.kind", AttributeValue::from("assistant")),
            ("pi.step.attempt", AttributeValue::from(1.0)),
        ]),
        |span| async move {
            span.set_attributes(span_attributes([(
                "pi.step.outcome",
                AttributeValue::from("succeeded"),
            )]));
            "harness-done"
        },
    )
    .await;
    assert_eq!(result, "harness-done");
}

#[tokio::test]
async fn typed_starter_composes_over_both_schemas() {
    let starter = agent_typed_span_starter();
    starter.start_span(
        "pi.harness.step",
        span_attributes([
            ("pi.lane.name", AttributeValue::from("main")),
            ("pi.operation.id", AttributeValue::from("operation")),
            ("pi.step.kind", AttributeValue::from("assistant")),
            ("pi.step.attempt", AttributeValue::from(1.0)),
        ]),
        |step_span, _child_starter| {
            step_span.set_attributes(span_attributes([(
                "pi.step.outcome",
                AttributeValue::from("succeeded"),
            )]));
        },
    );
}

#[test]
fn noop_context_helpers_run_without_panicking() {
    let context = pi_core::telemetry::noop_telemetry_context();
    context.start_span(
        pi_core::telemetry::SpanOptions::new("pi.harness.run").with("pi.lane.name", "main"),
        |_span| {},
    );
}
