//! Port of `pi-core/ai/src/models.generated.ts` and
//! `image-models.generated.ts`: the generated model catalogs.
//!
//! The TypeScript files are auto-generated by the upstream
//! `scripts/generate-models.ts` / `generate-image-models.ts` (which fetch
//! live provider data). The Rust port embeds the same generated data as
//! JSON, produced by `scripts/oracle/export-model-catalog.mts` running the
//! TypeScript oracle:
//!
//! ```sh
//! (cd pi-core/ai && npm run generate-models)
//! node --experimental-strip-types scripts/oracle/export-model-catalog.mts --write
//! ```

use std::collections::BTreeMap;
use std::sync::OnceLock;

use crate::ai::types::{ImagesModel, Model};

/// Provider-keyed model catalog: `{ [providerId]: { [modelId]: Model } }`.
/// The inner maps use `IndexMap` so model
/// lists keep the generator's insertion order — the observable
/// `Object.values` order in TypeScript.
pub type ProviderModels = BTreeMap<String, indexmap::IndexMap<String, Model>>;

/// Provider-keyed image model catalog.
pub type ProviderImagesModels = BTreeMap<String, indexmap::IndexMap<String, ImagesModel>>;

struct CatalogData {
    models: ProviderModels,
    image_models: ProviderImagesModels,
    generated_at: Option<String>,
}

fn catalog_data() -> &'static CatalogData {
    static DATA: OnceLock<CatalogData> = OnceLock::new();
    DATA.get_or_init(|| {
        let raw = include_str!("data/models.generated.json");
        #[derive(serde::Deserialize)]
        struct Payload {
            models: ProviderModels,
            #[serde(rename = "imageModels")]
            image_models: ProviderImagesModels,
            #[serde(rename = "generatedAt", default)]
            generated_at: Option<String>,
        }
        let payload: Payload = serde_json::from_str(raw).expect("generated model catalog parses");
        CatalogData {
            models: payload.models,
            image_models: payload.image_models,
            generated_at: payload.generated_at,
        }
    })
}

/// The manifest generation timestamp shared by all built-in catalogs, as
/// epoch milliseconds (`Date.parse` of `generatedAt`; `None` when absent or
/// unparseable). Port of `getBuiltinModelDataGeneratedAt`.
pub fn generated_at() -> Option<i64> {
    parse_rfc3339_millis(catalog_data().generated_at.as_deref()?)
}

/// Parses the RFC 3339 timestamps the oracle manifest emits
/// (`YYYY-MM-DDTHH:MM:SS(.fff)?Z`), mirroring `Date.parse` for that shape.
fn parse_rfc3339_millis(value: &str) -> Option<i64> {
    let parse_part = |text: &str, digits: usize| -> Option<i64> {
        if text.len() != digits || !text.bytes().all(|b| b.is_ascii_digit()) {
            return None;
        }
        text.parse::<i64>().ok()
    };
    let date_time = value.strip_suffix('Z')?;
    let [date, time] = date_time.split('T').collect::<Vec<_>>()[..2] else {
        return None;
    };
    let [year, month, day] = date.split('-').collect::<Vec<_>>()[..3] else {
        return None;
    };
    let (time, fraction) = match time.split_once('.') {
        Some((whole, fraction)) => (whole, Some(fraction)),
        None => (time, None),
    };
    let millis = match fraction {
        Some(fraction) => {
            if fraction.is_empty() || !fraction.bytes().all(|b| b.is_ascii_digit()) {
                return None;
            }
            let padded: String = fraction.chars().take(3).collect::<String>()
                + &"0".repeat(3usize.saturating_sub(fraction.len().min(3)));
            if padded.len() != 3 || !padded.bytes().all(|b| b.is_ascii_digit()) {
                return None;
            }
            padded.parse::<i64>().ok()?
        }
        None => 0,
    };
    let [hour, minute, second] = time.split(':').collect::<Vec<_>>()[..3] else {
        return None;
    };
    let (year, month, day) = (
        parse_part(year, 4)?,
        parse_part(month, 2)?,
        parse_part(day, 2)?,
    );
    let (hour, minute, second) = (
        parse_part(hour, 2)?,
        parse_part(minute, 2)?,
        parse_part(second, 2)?,
    );
    if !(1..=12).contains(&month) || !(1..=31).contains(&day) {
        return None;
    }
    // Days from civil (Howard Hinnant's algorithm).
    let years = if month <= 2 { year - 1 } else { year };
    let era = if years >= 0 { years } else { years - 399 } / 400;
    let year_of_era = years - era * 400;
    let month_shifted = if month > 2 { month - 3 } else { month + 9 };
    let day_of_year = (153 * month_shifted + 2) / 5 + day - 1;
    let day_of_era = year_of_era * 365 + year_of_era / 4 - year_of_era / 100 + day_of_year;
    let days = era * 146_097 + day_of_era - 719_468;
    Some((((days * 24 + hour) * 60 * 60 + minute * 60 + second) * 1000) + millis)
}

/// Port of the exported `MODELS` mapping.
pub fn models() -> &'static ProviderModels {
    &catalog_data().models
}

/// Port of the exported `IMAGE_MODELS` mapping.
pub fn image_models() -> &'static ProviderImagesModels {
    &catalog_data().image_models
}

/// All known provider ids present in the generated catalog.
pub fn provider_ids() -> Vec<String> {
    models().keys().cloned().collect()
}

/// The generated model list for one provider.
pub fn models_for_provider(provider: &str) -> Vec<Model> {
    models()
        .get(provider)
        .map(|models| models.values().cloned().collect())
        .unwrap_or_default()
}

/// The generated image model list for one provider.
pub fn image_models_for_provider(provider: &str) -> Vec<ImagesModel> {
    image_models()
        .get(provider)
        .map(|models| models.values().cloned().collect())
        .unwrap_or_default()
}

/// Port of `getImageModel`: exact provider+id image model lookup.
pub fn image_model(provider: &str, id: &str) -> Option<ImagesModel> {
    image_models()
        .get(provider)
        .and_then(|models| models.get(id))
        .cloned()
}

/// Port of `getImageProviders`: image model provider ids.
pub fn image_provider_ids() -> Vec<String> {
    image_models().keys().cloned().collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn catalog_contains_expected_providers_and_counts() {
        // Pinned against the TS oracle run that produced the embedded JSON
        // (`npm run generate-models` output). Counts move with upstream
        // regeneration; this asserts the catalog shape rather than exact
        // model counts.
        for provider in [
            "amazon-bedrock",
            "anthropic",
            "google",
            "google-vertex",
            "openai",
            "openai-codex",
            "openrouter",
            "azure-openai-responses",
        ] {
            assert!(
                models().contains_key(provider),
                "missing generated provider {provider}"
            );
            assert!(
                !models_for_provider(provider).is_empty(),
                "no models for {provider}"
            );
        }
        assert!(
            image_models().contains_key("openrouter"),
            "missing openrouter image models"
        );
        let anthropic = models_for_provider("anthropic");
        let first = &anthropic[0];
        assert_eq!(first.provider, "anthropic");
        assert!(!first.base_url.is_empty());
        assert!(first.context_window > 0);
    }

    #[test]
    fn generated_at_matches_the_oracle_manifest() {
        // Pinned against Date.parse of the oracle manifest timestamp.
        assert_eq!(generated_at(), Some(1_788_598_939_155));
        assert_eq!(parse_rfc3339_millis("not a date"), None);
        assert_eq!(
            parse_rfc3339_millis("2026-08-29T07:12:30Z"),
            Some(1_787_987_550_000)
        );
    }

    #[test]
    fn multi_api_catalogs_keep_generation_order() {
        // The generator groups multi-API providers by api; that order is the
        // observable Object.values order and must survive deserialization.
        let catalog = models_for_provider("fireworks");
        let fireworks: Vec<&str> = catalog.iter().map(|model| model.api.as_str()).collect();
        let last_anthropic = fireworks
            .iter()
            .rposition(|api| *api == "anthropic-messages")
            .expect("anthropic models");
        assert!(!fireworks[last_anthropic + 1..].contains(&"anthropic-messages"));
        assert!(
            fireworks[last_anthropic + 1..]
                .iter()
                .all(|api| *api == "openai-completions")
        );
        assert_eq!(
            catalog[0].id,
            "accounts/fireworks/models/deepseek-v4-flash-0731"
        );
    }
}
