//! Port of `pi-core/ai/src/models.generated.ts` and
//! `image-models.generated.ts`: the generated model catalogs.
//!
//! The TypeScript files are auto-generated by the upstream
//! `scripts/generate-models.ts` / `generate-image-models.ts` (which fetch
//! live provider data). The Rust port embeds the same generated data as
//! JSON, produced by `scripts/oracle/export-model-catalog.mts` running the
//! TypeScript oracle:
//!
//! ```sh
//! (cd pi-core/ai && npm run generate-models)
//! node --experimental-strip-types scripts/oracle/export-model-catalog.mts --write
//! ```

use std::collections::BTreeMap;
use std::sync::OnceLock;

use crate::ai::types::{ImagesModel, Model};

/// Provider-keyed model catalog: `{ [providerId]: { [modelId]: Model } }`.
pub type ProviderModels = BTreeMap<String, BTreeMap<String, Model>>;

/// Provider-keyed image model catalog.
pub type ProviderImagesModels = BTreeMap<String, BTreeMap<String, ImagesModel>>;

struct CatalogData {
    models: ProviderModels,
    image_models: ProviderImagesModels,
}

fn catalog_data() -> &'static CatalogData {
    static DATA: OnceLock<CatalogData> = OnceLock::new();
    DATA.get_or_init(|| {
        let raw = include_str!("data/models.generated.json");
        #[derive(serde::Deserialize)]
        struct Payload {
            models: ProviderModels,
            #[serde(rename = "imageModels")]
            image_models: ProviderImagesModels,
        }
        let payload: Payload = serde_json::from_str(raw).expect("generated model catalog parses");
        CatalogData {
            models: payload.models,
            image_models: payload.image_models,
        }
    })
}

/// Port of the exported `MODELS` mapping.
pub fn models() -> &'static ProviderModels {
    &catalog_data().models
}

/// Port of the exported `IMAGE_MODELS` mapping.
pub fn image_models() -> &'static ProviderImagesModels {
    &catalog_data().image_models
}

/// All known provider ids present in the generated catalog.
pub fn provider_ids() -> Vec<String> {
    models().keys().cloned().collect()
}

/// The generated model list for one provider.
pub fn models_for_provider(provider: &str) -> Vec<Model> {
    models()
        .get(provider)
        .map(|models| models.values().cloned().collect())
        .unwrap_or_default()
}

/// The generated image model list for one provider.
pub fn image_models_for_provider(provider: &str) -> Vec<ImagesModel> {
    image_models()
        .get(provider)
        .map(|models| models.values().cloned().collect())
        .unwrap_or_default()
}

/// Port of `getImageModel`: exact provider+id image model lookup.
pub fn image_model(provider: &str, id: &str) -> Option<ImagesModel> {
    image_models()
        .get(provider)
        .and_then(|models| models.get(id))
        .cloned()
}

/// Port of `getImageProviders`: image model provider ids.
pub fn image_provider_ids() -> Vec<String> {
    image_models().keys().cloned().collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn catalog_contains_expected_providers_and_counts() {
        // Pinned against the TS oracle run that produced the embedded JSON
        // (`npm run generate-models` output). Counts move with upstream
        // regeneration; this asserts the catalog shape rather than exact
        // model counts.
        for provider in [
            "amazon-bedrock",
            "anthropic",
            "google",
            "google-vertex",
            "openai",
            "openai-codex",
            "openrouter",
            "azure-openai-responses",
        ] {
            assert!(
                models().contains_key(provider),
                "missing generated provider {provider}"
            );
            assert!(
                !models_for_provider(provider).is_empty(),
                "no models for {provider}"
            );
        }
        assert!(
            image_models().contains_key("openrouter"),
            "missing openrouter image models"
        );
        let anthropic = models_for_provider("anthropic");
        let first = &anthropic[0];
        assert_eq!(first.provider, "anthropic");
        assert!(!first.base_url.is_empty());
        assert!(first.context_window > 0);
    }
}
